name: Esteira - Orquestração

on:
  workflow_dispatch:
  schedule:
    # 10:00, 12:00, 15:00, 19:00 (BRT) -> 13,15,18,22 UTC
    - cron: "0 13,15,18,22 * * *"

env:
  TZ: America/Sao_Paulo
  PYTHONUNBUFFERED: "1"

jobs:
  pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    concurrency:
      group: esteira-orquestracao
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Criar credenciais.json a partir do Secret
        run: |
          test -n "${{ secrets.GOOGLE_CREDENTIALS }}" || (echo "Secret GOOGLE_CREDENTIALS ausente" && exit 1)
          printf "%s" '${{ secrets.GOOGLE_CREDENTIALS }}' > credenciais.json

      - name: Executar pipeline (atualizar_replicar.py)
        run: |
          python atualizar_replicar.py | tee logs.txt

      - name: Anexar logs
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ github.run_id }}
          path: logs.txt
